apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saju-api-ingress
  namespace: saju
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.botfolio.cc
      secretName: saju-api-tls
  rules:
    - host: api.botfolio.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
